# Main background, empty for terminal default, need to be empty if you want transparent background
theme[main_bg]="#1a1b26"

# Main text color
theme[main_fg]="#a9b1d6"

# Title color for boxes
theme[title]="#a9b1d6"

# Highlight color for keyboard shortcuts
theme[hi_fg]="#7aa2f7"

# Background color of selected item in processes box
theme[selected_bg]="#31323c"

# Foreground color of selected item in processes box
theme[selected_fg]="#7aa2f7"

# Color of inactive/disabled text
theme[inactive_fg]="#414868"

# Color of text appearing on top of graphs, i.e uptime and current network graph scaling
theme[graph_text]="#b6bddc"

# Background color of the percentage meters
theme[meter_bg]="#31323c"

# Misc colors for processes box including mini cpu graphs, details memory graph and details status text
theme[proc_misc]="#b6bddc"

# CPU, Memory, Network, Proc box outline colors
theme[cpu_box]="#bb9af7"
theme[mem_box]="#9ece6a"
theme[net_box]="#f7768e"
theme[proc_box]="#7aa2f7"

# Box divider line and small boxes line color
theme[div_line]="#414868"

# Temperature graph color (Green -> Yellow -> Red)
theme[temp_start]="#9ece6a"
theme[temp_mid]="#e0af68"
theme[temp_end]="#f7768e"

# CPU graph colors (Teal -> Blue -> Magenta)
theme[cpu_start]="#7dcfff"
theme[cpu_mid]="#7aa2f7"
theme[cpu_end]="#bb9af7"

# Mem/Disk free meter
theme[free_start]="#bb9af7"
theme[free_mid]="#7aa2f7"
theme[free_end]="#7dcfff"

# Mem/Disk cached meter
theme[cached_start]="#7aa2f7"
theme[cached_mid]="#7dcfff"
theme[cached_end]="#bb9af7"

# Mem/Disk available meter
theme[available_start]="#e0af68"
theme[available_mid]="#f7768e"
theme[available_end]="#f7768e"

# Mem/Disk used meter (Green -> Teal -> Blue)
theme[used_start]="#9ece6a"
theme[used_mid]="#7dcfff"
theme[used_end]="#7aa2f7"

# Download graph colors
theme[download_start]="#e0af68"
theme[download_mid]="#f7768e"
theme[download_end]="#f7768e"

# Upload graph colors (Green -> Teal -> Blue)
theme[upload_start]="#9ece6a"
theme[upload_mid]="#7dcfff"
theme[upload_end]="#7aa2f7"

# Process box color gradient for threads, mem and cpu usage
theme[process_start]="#7dcfff"
theme[process_mid]="#7aa2f7"
theme[process_end]="#bb9af7"

# Graph gradient colors (spectrum shades from background to foreground)
theme[gradient_color_0]="#1a1b26"
theme[gradient_color_1]="#31323c"
theme[gradient_color_2]="#31323c"
theme[gradient_color_3]="#414868"
theme[gradient_color_4]="#7f85a1"
theme[gradient_color_5]="#a9b1d6"
theme[gradient_color_6]="#b6bddc"
theme[gradient_color_7]="#bfc5e0"
